version: "2.2"

services:
  cassandra-db:
    build: cassandra-node
    container_name: cassandra-db
    ports :
      - 7000:7000
      - 7001:7001
      - 7199:7199
      - 9042:9042
      - 9160:9160
    environment:
      - CASSANDRA_DC=DC1
      - CASSANDRA_NODE_TO_WAIT=cassandra-db
    volumes:
      - ./datasets:/datasets
    mem_limit: 2G

  cassandra-db-1:
    build: cassandra-node
    container_name: cassandra-db-1
    links:
      - cassandra-db:seed
    ports:
      - 9142:9042
    environment:
      - CASSANDRA_SEEDS=seed
      - CASSANDRA_DC=DC2
      - CASSANDRA_NODE_TO_WAIT=cassandra-db
    mem_limit: 2G